## Esse cluster serve para requisições feitas dentro do mesmo cluster, sem
## expor a internet
apiVersion: v1
kind: Service
metadata: 
    name: clusterip-service
spec:
    selector:
     app: fiapapipod
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80